name: React Vite Frontend
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.18
          
      - name: Moving into the right directory
        run: cd frontend

      - name: Install dependencies
        run: npm install

      - name: Running tests
        run: npm run test